<?php

$plugin = array(
  'title' => t('Kopernikus 3-2-4-1'),
  'category' => t('Kopernikus Custom Layouts'),
  'icon' => 'kopernikus_3_2_4_1.png',
  'theme' => 'kopernikus_3_2_4_1',
  'admin css' => 'kopernikus_3_2_4_1.css',
  'regions' => array(
    'top_left' => t('Top Left'),
    'top_middle' => t('Top Middle'),
    'top_right' => t('Top Right'),
    'middle_left' => t('Middle Left'),
    'middle_right' => t('Middle Right'),
    'bottom_1' => t('Bottom 1'),
    'bottom_2' => t('Bottom 2'),
    'bottom_3' => t('Bottom 3'),
    'bottom_4' => t('Bottom 4'),
    'footer' => t('Footer'),
  ),
);
