<?php

$plugin = array(
  'title' => t('Kopernikus 1-3-2-1'),
  'category' => t('Kopernikus Custom Layouts'),
  'icon' => 'kopernikus_1_3_2_1.png',
  'theme' => 'kopernikus_1_3_2_1',
  'admin css' => 'kopernikus_1_3_2_1.css',
  'regions' => array(
    'top' => t('Top'),
    'left' => t('Left'),
    'middle' => t('Middle'),
    'right' => t('Right'),
    'bottom_1' => t('Bottom 1'),
    'bottom_2' => t('Bottom 2'),
    'footer' => t('Footer'),
  ),
);
