<?php

$plugin = array(
  'title' => t('Kopernikus 3-1-4'),
  'category' => t('Kopernikus Custom Layouts'),
  'icon' => 'kopernikus_3_1_4.png',
  'theme' => 'kopernikus_3_1_4',
  'admin css' => 'kopernikus_3_1_4.css',
  'regions' => array(
    'top_left' => t('Top Left'),
    'top_middle' => t('Top Middle'),
    'top_right' => t('Top Right'),
    'middle' => t('Middle'),
    'bottom_1' => t('Bottom 1'),
    'bottom_2' => t('Bottom 2'),
    'bottom_3' => t('Bottom 3'),
    'bottom_4' => t('Bottom 4'),
  ),
);
