<?php

//Implements hook_theme_registry_alter()
function ckeditor_config_theme_registry_alter(&$theme_registry) {
	if(isset($theme_registry['imce_page'])) {
		$theme_registry['imce_page']['path'] = drupal_get_path('module', 'ckeditor_config');
	}
}
//Implements hook_wysiwyg_editor_settings_alter().
function ckeditor_config_wysiwyg_editor_settings_alter(&$settings, $context) {
  if ($context['profile']->editor == 'ckeditor') {
		$settings['customConfig'] = base_path() . drupal_get_path('module', 'ckeditor_config') . '/js/ckeditor_config.js';
  }
}