<?php

$plugin = array(
  'title' => t('Kopernikus 1-3-3-1'),
  'category' => t('Kopernikus Custom Layouts'),
  'icon' => 'kopernikus_1_3_3_1.png',
  'theme' => 'kopernikus_1_3_3_1',
  'admin css' => 'kopernikus_1_3_3_1.css',
  'regions' => array(
    'header' => t('Header'),
    'top_left' => t('Top Left'),
    'top_middle' => t('Top Middle'),
    'top_right' => t('Top Right'),
    'bottom_left' => t('Bottom Left'),
    'bottom_middle' => t('Bottom Middle'),
    'bottom_right' => t('Bottom Right'),
    'footer' => t('Footer'),
  ),
);
